# Most of this was copied/adapted from Erik Zelikman's blog.
# https://github.com/ezelikman/ezelikman.github.io

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

name: "Eric Werner's Website"
author:
  name: "Rylan Schaeffer"
  email: "reawern@outlook.com"
  twitter: "eriwern"
plugins:
  - jekyll-feed

title: Eric Werner
description: "'Fuck it, we ball.'"
theme: jekyll-theme-minimal # minima
logo: index/profile_pic.jpg
show_downloads: false
baseurl: ""
#google_analytics: G-1VJF4S0L85
markdown: kramdown
kramdown:
  math_engine: mathjax
collections_dir: collections
collections:
  blog_posts:
    output: true
  blog_drafts:
    output: false
  own_research:
    output: true
  kernel_papers:
    output: true
  kernel_papers_drafts:
    output: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/