# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

remote_theme: pages-themes/architect@v0.2.0
#theme: jekyll-theme-minimal # minimal

name: "Eric Werner's Website"
author:
  name: "Eric Werner"
  email: "eawern@outlook.com"
  twitter: "eriwern"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

description: >- # this means to ignore newlines until "baseurl:"
  '“Contentment is as rare among men as it is natural among animals.
    No form of government has ever satisfied its subjects”'
  -Caesar and the Christ, Will Durant
#twitter_username: eriwern
github_username:  ewernn
logo: index/profile_pic.jpg
show_downloads: false
baseurl: ""
google_analytics: G-1VJF4S0L85
markdown: kramdown
kramdown:
  math_engine: mathjax
collections_dir: collections
collections:
  blog_posts:
    output: true
  blog_drafts:
    output: false
  own_research:
    output: true
  kernel_papers:
    output: true
  kernel_papers_drafts:
    output: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/